#Stage
CELL_SIZE = 25
GRID_WIDTH = 10
GRID_HEIGHT = 10
down = 0
up = 1
right = 2 
left = 3

#RNN
STATE_SIZE = GRID_WIDTH+GRID_HEIGHT+4
HIDDEN_SIZE = 128
ACTION_SIZE = 4
BATCH_SIZE = 32

#Reward & penalty
MOVE_PENALTY = -5
APPROACH_PENALTY = -1
GREEN_APPLE_REWARD = 300.0
RED_APPLE_PENALTY = -150.0
APPROACH_GREEN_APPLE_REWARD = 0.5
MOVE_AWAY_GREEN_APPLE_PENALTY = -0.5
APPROACH_RED_APPLE_PENALTY = -0.5
MOVE_AWAY_RED_APPLE_REWARD = +0.5
GAME_OVER_PENALTY = -800.0

